### ISSUE TITLE
My auctions with character below level 10

### ISSUE THREAD

**Issue by mithandir** [ukon1990/wow-auction-helper#20]
Can you add a feature to show "My Auctions" for characters below Level 10? You could probably link the auction data to the character by name.

**Comment by ukon1990** [comment]
Thank you for reporting this.
Il'l get this fixed when I get home from my vacation (maybe before).

**Comment by ukon1990** [comment]
Hi, when you added the character that was below level 10. Did you check the "Below level 10" checkbox?

It does seem to work for me, when that one is checked ( as it's supposed to). I should probably give the user better feedback, in cases where the character is not found in blizzards API.

As you might know, characters below level 10 are not available through the blizzard API. That is why I added the checkbox. So that not every misspelled character name gets treated as one.

**Comment by mithandir** [comment]
I thought I did check the box.

Now it is indeed working. Thank you.

**Comment by ukon1990** [comment]
No problem. I'm glad that it is working!
I'm thinking of keeping it open until I've made improvements to adding sub level 10 characters.

**Comment by ukon1990** [comment]
Users will now get a popup upon success or failure when it comes to adding a character. And the name of the character, will no longer be removed from the input field if the character is not found.
