### ISSUE TITLE
Realm drop down not working

### ISSUE THREAD

**Issue by Tharic99** [ukon1990/wow-auction-helper#42]
On the step 1 page, selecting either America or Europe, the Realm drop down is not currently doing anything. 

Language sets to English fine, but can't move past the Realm drop down.

Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by ukon1990** [comment]
Hi, thank you for reporting this.

It does seem like blizzard are currently having some issues with their API at the moment.

Getting 500, 502, 504 responses from blizzard from different api endpoints.

It is currently working for me with the realm list. Does it work for you now?

If not, you can manually add this by opening the console, go to application, local storage and the app's url.

add the key region give the value eu or us.
Add a key for realm and give it your realm name in lower case with - instead of spaces and remove '.

eg: Blade's Edge would be blades-edge

**Comment by Tharic99** [comment]
Ah, I figured out what it is with you recommending to go to the console. I'm running this from work, and work has the battle.net site blocked. I can see in my console I'm getting a 403 error (URL Blocked) as a result.

Oh well. Thanks for checking though and I'll check it out from home later. I'll close this issue now.

**Comment by ukon1990** [comment]
But I have added some fall back realm files, in case their endpoint does not work another time (v 2.171.4)
